### ISSUE TITLE
Inline in-app message (aka embedded in-app messages)

### ISSUE THREAD

**Issue by jbtheard** [customerio/customerio-reactnative#121]
**Is your feature request related to a problem? Please describe.**
Your doc mention inline events available to iOS and Android [here](https://customer.io/docs/send-in-app-message/#display-and-position) but in the [linked Gist doc](https://docs.gist.build/libraries/react-native#important), it appears the feature hasn't been implemented (but on the Gist team roadmap?)

**Describe the solution you'd like**
a way to use inline in-app message similar to the web; by replacing a View placeholder (or even a specific View from customerio-reactnative package ?)

**Describe alternatives you've considered**
using modals but it's not as elegant.
I currently use a custom in-app message system that triggers an in-app message based on CIO campaign but that's a lot of custom code.

**Additional context**
Happy to test the feature when you guys are working on it.

**Comment by levibostian** [comment]
Thanks for sending in this message, @jbtheard. 

I do understand that in order to accomplish this feature today, it requires custom code. Thanks for putting in the effort to do that in your app. 

I cannot give you a time frame on when this feature would be released. Note that I have documented this feature request with the mobile in-app team and we will be prioritizing it from there. 

We especially appreciate you willing to test this feature. If you could, send a good email address to contact you to `win@customer.io` and I'll add that email address to the internal feature request. That will be the easiest way for us to get you testing it.

**Comment by levibostian** [comment]
Because this feature is documented internally as a feature, I will close this issue. However, the conversation can continue on.
