### ISSUE TITLE
In App messages doesn't unfocus input

### ISSUE THREAD

**Issue by beqramo** [customerio/customerio-reactnative#176]
Hi,

When in app message is sent, library don't remove the keyboard, because of that it looks terrible.
This needs to be fixed from the library level.

**Comment by beqramo** [comment]
1. yes. because you can't overlay on the keyboard and when it is a modal like in app message it looks ugly.
2. it was seen on ios i haven't test on android but if there is no logic it will be same.
3.  I can't find it now, but the situation was like this: I'm showing the input with a keyboard and at that time we are triggering in app is visible on top of the viewable area but the keyboard isn't visible still. so it doesn't make sense to have the keyboard opened

**Comment by beqramo** [comment]
any update?

**Comment by lj-cio** [comment]
Hi @beqramo, thanks for your patience here and for the reminder. The issue that @mrehan27 created on your behalf has been scoped and we're optimistic about an approach to fix the issue, but have so far prioritized in-app and SDK improvements that have pushed the changes needed here further out.  

If our priorities seem wrong or we're missing additional context, would you be [open to a quick call](https://calendly.com/lynnho/cio-product-feedback) to better understand your use case and how your app and flows are impacted?

**Comment by ami-aman** [comment]
Hi @beqramo 

Good news! The fix for this issue is now available in version [4.0.2](https://github.com/customerio/customerio-reactnative/releases/tag/4.0.2). This version of `customerio-reactnative` also includes support for CDP (Customer.io Data Pipelines). If you haven’t upgraded to version `4.x` yet, please refer to our [migration guide](https://docs.customer.io/sdk/react-native/whats-new/4.x-upgrade/) and [quick start guide](https://docs.customer.io/sdk/react-native/quick-start-guide/) for assistance.

With the release of this fix, we’re closing this issue. However, feel free to open a new issue if you have any questions!
