### ISSUE TITLE
Support for React Native Web

### ISSUE THREAD

**Issue by sreuter** [customerio/customerio-reactnative#57]
**Is your feature request related to a problem? Please describe.**
Right now it seems I'd need to install this module for the Android and iOS targets of React Native, and then also add the web SDK to support React Native Web. It would be great if this package could automatically use the web SDK for React Native Web.

**Describe the solution you'd like**
By installing `customerio-reactnative`, I can use it on iOS, Android and Web alike. No extra fiddling is needed.

**Describe alternatives you've considered**
Doing everything manually that this module could handle automagically.

**Comment by spooksmus** [comment]
Hi @ami-aman and team,
I came here to make a similar request. It would be neat if the SDK had support for Capacitor - the JS-based native runtime built by the Ionic Team that enables native app support. Capacitor allows for writing plugins written in native iOS / Android code (Swift, Kotlin). If there was an officially maintained customer.io Capacitor plugin that was offered which serves as a wrapper for the native iOS and Android SDK, then it would allow all those who've built their application with Ionic / Capacitor to leverage customer.io (which is not just restricted to React, since Ionic supports Angular, Vue, and vanilla JS). If you feel this is sufficiently different than the original request on this ticket, I can open a new one :)

**Comment by ami-aman** [comment]
Hi @spooksmus 

Thank you for reaching out. I would like to let you know that we already have few requests for Ionic and this sounds like a new feature request. I would really appreciate if you could open a new request with same details as you mentioned in your comment ?

**Comment by jbtheard** [comment]
+1
much needed for cross platforms apps that include web

**Comment by Shahroz16** [comment]
Closing this ticket as the feature request has been noted internally. We'll be sure to keep you updated on our progress. Thank you again for writing in.

**Comment by fershibli** [comment]
+1 needed this so much
